-- COMMENTS
INSERT INTO comments (user_id, post_id, text, created_at) VALUES
(2,1,'Amazing ride! Which route did you take?',NOW()),
(3,1,'Pune roads are the best!',NOW()),
(1,2,'Stunning photo Priya! 😍',NOW()),
(4,2,'Lonavala is always beautiful!',NOW()),
(5,3,'What a match! Brilliant game!',NOW()),
(6,3,'India India India! 🏏',NOW()),
(1,4,'Recipe please! Looks delicious 😋',NOW()),
(7,4,'Misal Pav is life ❤️',NOW()),
(8,5,'Take me with you next time!',NOW()),
(9,5,'Mahabaleshwar strawberries are the best!',NOW()),
(10,6,'You are such an inspiration!',NOW()),
(11,7,'Congratulations Amol! All the best 🚀',NOW()),
(12,7,'What does your startup do?',NOW()),
(13,8,'This is so beautiful Rutuja!',NOW()),
(14,9,'I was there last night! Amazing show!',NOW()),
(15,10,'Respect! I cant even wake up at 7 😂',NOW()),
(16,11,'Which game are you playing?',NOW()),
(17,12,'Looking gorgeous Dipali! 😍',NOW()),
(18,13,'Great news! Hard work pays off 🌾',NOW()),
(19,14,'One of my favorite books too!',NOW()),
(20,15,'Send me some please! 😄',NOW()),
(1,16,'Incredible performance Shruti! 💃',NOW()),
(2,17,'Keep it up! 🎶',NOW()),
(3,18,'Mumbai rains are magical ☔',NOW()),
(4,19,'Where did you get that costume?',NOW()),
(5,20,'Such a noble thing to teach kids 🙏',NOW()),
(6,21,'Ganesh festival is the best! 🥁',NOW()),
(7,22,'Your dedication is inspiring!',NOW()),
(8,23,'Congratulations! Well deserved 🏆',NOW()),
(9,24,'Safety first on site! 🚧',NOW()),
(10,25,'New projects mean more jobs!',NOW()),
(11,26,'Dam construction is tough work!',NOW()),
(12,27,'Team lunch looks delicious 😄',NOW()),
(13,28,'Shirdi darshan is always peaceful 🙏',NOW()),
(14,29,'Congratulations Senior Engineer! 🎉',NOW()),
(15,30,'AutoCAD skills are impressive!',NOW()),
(16,31,'Yoga at dawn is the best feeling!',NOW()),
(17,32,'I want to join the workshop!',NOW()),
(18,33,'Signing up for Monday batch!',NOW()),
(19,34,'Lonavala retreat sounds amazing!',NOW()),
(20,35,'That breakfast looks so healthy 😍',NOW()),
(1,36,'Kids yoga is such a great initiative!',NOW()),
(2,37,'Happy International Yoga Day! 🌍',NOW()),
(3,38,'100 days is incredible dedication!',NOW()),
(4,39,'Subscribed to your channel! 📹',NOW()),
(5,40,'Wari festival coverage was amazing!',NOW()),
(6,41,'Great interview Pravin!',NOW()),
(7,42,'Finally good news for Marathwada!',NOW()),
(8,43,'Mantralaya press meet must be intense!',NOW()),
(9,44,'Kumbh Mela reporting is incredible!',NOW()),
(10,45,'Well deserved award Pravin! 🏆',NOW()),
(11,46,'Flood relief work is commendable 🌊',NOW()),
(12,47,'Vidarbha farmers need more support 🌾',NOW()),
(13,48,'Looking forward to your Lokmat column!',NOW()),
(14,49,'Health camps save lives! Thank you 🏥',NOW()),
(15,50,'God bless your hands doctor! 🙏',NOW()),
(16,51,'Diabetes awareness is so important!',NOW()),
(17,52,'Such a kind heart Ashwini! 🤝',NOW()),
(18,53,'Blood donation is a great cause ❤️',NOW()),
(19,54,'New OPD wing is a great facility!',NOW()),
(20,55,'Medical conferences are so enriching!',NOW()),
(1,56,'Happy World Health Day! 🌍',NOW()),
(2,57,'Training nurses is so important 👩‍⚕️',NOW()),
(3,58,'Best doctor of Nagpur! Well deserved 🏆',NOW()),
(22, 60, 'Welcome to the developer world! 🚀', NOW()),
(23, 60, 'All the best Aryan!', NOW()),
(21, 61, 'Java is amazing!', NOW()),
(24, 61, 'Keep learning! 💪', NOW()),
(25, 62, 'Congratulations on your first API! 🎉', NOW()),
(22, 63, 'Happy Ganesh Chaturthi! 🙏', NOW()),
(21, 63, 'Ganpati Bappa Morya! 🙏', NOW()),
(26, 64, 'Chai and code is life ☕', NOW()),
(27, 65, 'Shirdi is so peaceful!', NOW()),
(21, 66, 'Nashik is beautiful 🌅', NOW()),
(22, 67, 'Maharashtrian food is the best! 🍱', NOW()),
(23, 68, 'Nashik market is amazing 🛍️', NOW()),
(24, 69, 'Happy Diwali! 🪔', NOW()),
(25, 70, 'Such a sweet family moment 📚', NOW()),
(26, 71, 'Evening walks are so refreshing 🌳', NOW()),
(27, 72, 'Work life balance is important 😎', NOW()),
(21, 73, 'Cricket is life! 🏏', NOW()),
(22, 74, 'Trimbakeshwar darshan is divine 🙏', NOW()),
(23, 75, 'Chai and newspaper is my morning ritual ☕', NOW()),
(24, 76, 'Annual day memories are precious 🎭', NOW()),
(25, 77, 'Gangapur dam is beautiful 🌊', NOW()),
(26, 78, 'Puran Poli is my favorite! 😋', NOW()),
(27, 79, 'Rangoli looks amazing 🎨', NOW()),
(21, 80, 'Family is everything ❤️', NOW());