-- POSTS
INSERT INTO posts (user_id, caption, image_url, like_count, comment_count, created_at) VALUES
(1,  'Exploring Pune on my bike today! 🏍️', NULL, 0, 0, NOW()),
(2,  'Captured the sunset at Lonavala 📸', NULL, 0, 0, NOW()),
(3,  'India won the match! What a game! 🏏', NULL, 0, 0, NOW()),
(4,  'Tried making Misal Pav at home 😋', NULL, 0, 0, NOW()),
(5,  'Road trip to Mahabaleshwar this weekend! 🚗', NULL, 0, 0, NOW()),
(6,  'Teaching kids is the best job ever ❤️', NULL, 0, 0, NOW()),
(7,  'Launched my new startup today! 🚀', NULL, 0, 0, NOW()),
(8,  'New painting finished after 3 days 🎨', NULL, 0, 0, NOW()),
(9,  'Performed at Pune Music Fest last night 🎸', NULL, 0, 0, NOW()),
(10, 'Morning run at 5am 10km done 💪', NULL, 0, 0, NOW()),
(11, 'Finally beat this game on hard mode 🎮', NULL, 0, 0, NOW()),
(12, 'New outfit for Diwali 🪔✨', NULL, 0, 0, NOW()),
(13, 'Good harvest season this year 🌾', NULL, 0, 0, NOW()),
(14, 'Finished reading Shivaji Maharaj biography 📖', NULL, 0, 0, NOW()),
(15, 'Made authentic Kolhapuri chicken today 🍗', NULL, 0, 0, NOW()),
(16, 'Performed Lavani at cultural fest 💃', NULL, 0, 0, NOW()),
(16, 'Just finished my dance practice session 🎶', NULL, 0, 0, NOW()),
(16, 'Mumbai rains are so beautiful today ☔', NULL, 0, 0, NOW()),
(16, 'New dance costume arrived today 👗', NULL, 0, 0, NOW()),
(16, 'Teaching Bharatnatyam to kids this weekend 🙏', NULL, 0, 0, NOW()),
(16, 'Performed at Ganesh festival last night 🥁', NULL, 0, 0, NOW()),
(16, 'Morning riyaz done! Feeling energetic 🌅', NULL, 0, 0, NOW()),
(16, 'Got selected for state level dance competition 🏆', NULL, 0, 0, NOW()),
(17, 'Bridge construction project completed ✅', NULL, 0, 0, NOW()),
(17, 'Site inspection done at Nashik highway 🚧', NULL, 0, 0, NOW()),
(17, 'New project kickoff meeting today 📋', NULL, 0, 0, NOW()),
(17, 'Concrete pouring started at the dam site 🏗️', NULL, 0, 0, NOW()),
(17, 'Team lunch after successful project delivery 🍽️', NULL, 0, 0, NOW()),
(17, 'Visited Shirdi with family this weekend 🙏', NULL, 0, 0, NOW()),
(17, 'Got promoted to Senior Engineer today! 🎉', NULL, 0, 0, NOW()),
(17, 'AutoCAD drawing finalized for new flyover 📐', NULL, 0, 0, NOW()),
(18, 'Morning yoga session with 50 students 🧘', NULL, 0, 0, NOW()),
(18, 'Pranayama workshop was a huge success! 🌬️', NULL, 0, 0, NOW()),
(18, 'New batch starting from Monday! Join us 🙌', NULL, 0, 0, NOW()),
(18, 'Meditation retreat at Lonavala this weekend 🏔️', NULL, 0, 0, NOW()),
(18, 'Healthy breakfast after yoga 🥗', NULL, 0, 0, NOW()),
(18, 'Teaching kids yoga at local school today 🏫', NULL, 0, 0, NOW()),
(18, 'International Yoga Day celebration at Pune 🌍', NULL, 0, 0, NOW()),
(18, 'My students completed 100 day yoga challenge 🏅', NULL, 0, 0, NOW()),
(18, 'New YouTube channel launched for yoga tips 📹', NULL, 0, 0, NOW()),
(19, 'Covered the Wari festival for our paper 📰', NULL, 0, 0, NOW()),
(19, 'Interview with the Aurangabad collector today 🎙️', NULL, 0, 0, NOW()),
(19, 'Breaking news new highway approved for Marathwada 🛣️', NULL, 0, 0, NOW()),
(19, 'Attended press conference at Mantralaya today 🏛️', NULL, 0, 0, NOW()),
(19, 'Reporting live from Nashik Kumbh Mela 🕉️', NULL, 0, 0, NOW()),
(19, 'Award for best regional journalism received 🏆', NULL, 0, 0, NOW()),
(19, 'Covered flood relief operations in Kolhapur 🌊', NULL, 0, 0, NOW()),
(19, 'Special report on farmers of Vidarbha published 🌾', NULL, 0, 0, NOW()),
(19, 'New column starting in Lokmat from next week ✍️', NULL, 0, 0, NOW()),
(20, 'Free health camp organized in Nagpur 🏥', NULL, 0, 0, NOW()),
(20, 'Performed successful surgery today 🙏', NULL, 0, 0, NOW()),
(20, 'Awareness drive for diabetes in rural areas 💉', NULL, 0, 0, NOW()),
(20, 'Donated medicines to tribal villages near Nagpur 🤝', NULL, 0, 0, NOW()),
(20, 'Blood donation camp at our hospital today ❤️', NULL, 0, 0, NOW()),
(20, 'New OPD wing inaugurated at our hospital 🏨', NULL, 0, 0, NOW()),
(20, 'Attending medical conference in Mumbai tomorrow ✈️', NULL, 0, 0, NOW()),
(20, 'World Health Day celebration at our clinic 🌍', NULL, 0, 0, NOW()),
(20, 'Trained 20 nurses in advanced patient care 👩‍⚕️', NULL, 0, 0, NOW()),
(20, 'Got recognition as best doctor of Nagpur 2026 🏆', NULL, 0, 0, NOW()),
(21, 'First day as a Spring Boot developer! 🚀', NULL, 0, 0, NOW()),
(21, 'Learning Java every single day 💻', NULL, 0, 0, NOW()),
(21, 'Built my first REST API today! 🎉', NULL, 0, 0, NOW()),

(22, 'Ganesh Chaturthi celebrations at home 🙏', NULL, 0, 0, NOW()),
(22, 'Coding late night with chai ☕', NULL, 0, 0, NOW()),
(22, 'Family trip to Shirdi this weekend 🕉️', NULL, 0, 0, NOW()),

(23, 'Morning walk at Nashik riverside 🌅', NULL, 0, 0, NOW()),
(23, 'Cooking special Maharashtrian thali today 🍱', NULL, 0, 0, NOW()),
(23, 'Weekend shopping at Nashik market 🛍️', NULL, 0, 0, NOW()),

(24, 'Happy Diwali to everyone! 🪔✨', NULL, 0, 0, NOW()),
(24, 'Teaching my kids maths today 📚', NULL, 0, 0, NOW()),
(24, 'Evening walk with family 🌳', NULL, 0, 0, NOW()),

(25, 'Office work done! Time to relax 😎', NULL, 0, 0, NOW()),
(25, 'Cricket match with friends today 🏏', NULL, 0, 0, NOW()),
(25, 'Visited Trimbakeshwar temple 🙏', NULL, 0, 0, NOW()),

(26, 'Sunday morning chai and newspaper ☕📰', NULL, 0, 0, NOW()),
(26, 'Kids school annual day celebration 🎭', NULL, 0, 0, NOW()),
(26, 'Family picnic at Gangapur dam 🌊', NULL, 0, 0, NOW()),

(27, 'Cooking Puran Poli for festival 😋', NULL, 0, 0, NOW()),
(27, 'Evening rangoli for Diwali 🎨', NULL, 0, 0, NOW()),
(27, 'Family get together at home ❤️', NULL, 0, 0, NOW());